/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ObjectsIdRouteImport } from './routes/objects.$id'
import { Route as RecordsIdRouteImport } from './routes/records.$id'
import { Route as RecordsNewRouteImport } from './routes/records.new'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsAllRouteImport } from './routes/reports.all'
import { Route as ReportsDetailRouteImport } from './routes/reports.detail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectsIdRoute = ObjectsIdRouteImport.update({
  id: '/objects/$id',
  path: '/objects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIdRoute = RecordsIdRouteImport.update({
  id: '/records/$id',
  path: '/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsNewRoute = RecordsNewRouteImport.update({
  id: '/records/new',
  path: '/records/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAllRoute = ReportsAllRouteImport.update({
  id: '/reports/all',
  path: '/reports/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsDetailRoute = ReportsDetailRouteImport.update({
  id: '/reports/detail',
  path: '/reports/detail',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/records/$id': typeof RecordsIdRoute
  '/records/new': typeof RecordsNewRoute
  '/reports/all': typeof ReportsAllRoute
  '/reports/detail': typeof ReportsDetailRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/records/$id': typeof RecordsIdRoute
  '/records/new': typeof RecordsNewRoute
  '/reports/all': typeof ReportsAllRoute
  '/reports/detail': typeof ReportsDetailRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/objects/$id': typeof ObjectsIdRoute
  '/records/$id': typeof RecordsIdRoute
  '/records/new': typeof RecordsNewRoute
  '/reports/all': typeof ReportsAllRoute
  '/reports/detail': typeof ReportsDetailRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/messages'
    | '/profile'
    | '/objects/$id'
    | '/records/$id'
    | '/records/new'
    | '/reports/all'
    | '/reports/detail'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/messages'
    | '/profile'
    | '/objects/$id'
    | '/records/$id'
    | '/records/new'
    | '/reports/all'
    | '/reports/detail'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/messages'
    | '/profile'
    | '/objects/$id'
    | '/records/$id'
    | '/records/new'
    | '/reports/all'
    | '/reports/detail'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  ObjectsIdRoute: typeof ObjectsIdRoute
  RecordsIdRoute: typeof RecordsIdRoute
  RecordsNewRoute: typeof RecordsNewRoute
  ReportsAllRoute: typeof ReportsAllRoute
  ReportsDetailRoute: typeof ReportsDetailRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objects/$id': {
      id: '/objects/$id'
      path: '/objects/$id'
      fullPath: '/objects/$id'
      preLoaderRoute: typeof ObjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$id': {
      id: '/records/$id'
      path: '/records/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof RecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/new': {
      id: '/records/new'
      path: '/records/new'
      fullPath: '/records/new'
      preLoaderRoute: typeof RecordsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/all': {
      id: '/reports/all'
      path: '/reports/all'
      fullPath: '/reports/all'
      preLoaderRoute: typeof ReportsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/detail': {
      id: '/reports/detail'
      path: '/reports/detail'
      fullPath: '/reports/detail'
      preLoaderRoute: typeof ReportsDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  ObjectsIdRoute: ObjectsIdRoute,
  RecordsIdRoute: RecordsIdRoute,
  RecordsNewRoute: RecordsNewRoute,
  ReportsAllRoute: ReportsAllRoute,
  ReportsDetailRoute: ReportsDetailRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
